CREATE TABLE public.product (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50),
    description character varying(50),
    image_path character varying(255),
    price integer,
    amount_in_stock integer,
    tag character varying(50),
    public_id uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    product_status integer DEFAULT 0
);

CREATE TABLE public.session (
    session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    analytics_id uuid
);

CREATE TABLE public.cart (
    cart_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint,
    product_id bigint,
    amount_selected integer,
    status integer,
    CONSTRAINT cart_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id),
    CONSTRAINT cart_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.session(session_id)
);
