create table product
(
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(50),
    description     varchar(50),
    image_path      varchar(255),
    price           integer,
    amount_in_stock integer,
    tag             varchar(50),
    public_id       uuid default gen_random_uuid() not null,
    product_status  integer default 0
);

create table session
(
    session_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_timestamp timestamp default CURRENT_TIMESTAMP,
    analytics_id    uuid
);

create table cart
(
    cart_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      bigint references session,
    product_id      bigint references product,
    amount_selected integer,
    status          integer
);

create table spring_session
(
    primary_id            char(36) not null
        constraint spring_session_pk
            primary key,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100)
);

create unique index spring_session_ix1
    on spring_session (session_id);

create index spring_session_ix2
    on spring_session (expiry_time);

create index spring_session_ix3
    on spring_session (principal_name);

create table spring_session_attributes
(
    session_primary_id char(36)     not null
        constraint spring_session_attributes_fk
            references spring_session
            on delete cascade,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
    constraint spring_session_attributes_pk
        primary key (session_primary_id, attribute_name)
);