name: "fast feedback workflow"
on:
  push:
    branches:
      - feature/**
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: list files of repository
        run: |
          echo "repository contains following files"
          tree
